# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2011

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /guestbook/

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  fancybox: true

copyright:
  enable: false
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

reward:
  enable: false
  qrCode:
    wechat: 
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  github: https://github.com/yrom
  weibo: http://weibo.com/yrom
  google: https://plus.google.com/+YromWang?rel=author
  email: hi@yongyong.wang
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  zhihu:
  douban:
  pocket:
  tumblr:

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 
# Baidu Verification
baidu_verification: 

# Google Analytics
google_analytics: UA-37232312-1
# Google Verification
google_verification:

# Disqus
disqus_shortname: yrom

#Changyan
changyan:
  appid:
  appkey:

# ===========================================
# Version
# ===========================================
version: 2.5.1
